version: "3.1"

services:
  database:
    container_name: pg_database
    image: postgres
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB_NAME
    restart: always
    networks:
      - botnet
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql

  django:
    container_name: djangoproject
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - database

  test_bot:
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - django

networks:
  botnet:
    driver: bridge