version: "3.1"

services:
  test_db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB_NAME
    restart: always
    networks:
      - botnet
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql

  test_bot:
    build:
      context: .
    command: python app.py
    restart: always
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - database

networks:
  botnet:
    driver: bridge