version: "3.1"

services:
  db:
    container_name: test_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./postgres:/var/lib/postgresql

  tgbot:
    container_name: test_bot
    build:
      context: .
    command: python app.py
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    env_file:
      - ".env"
    volumes:
      - .:/src
    depends_on:
      - db

networks:
  botnet:
    driver: bridge