# Generated by Django 3.2.11 on 2022-01-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='ID Пользователя')),
                ('name', models.CharField(max_length=100, verbose_name='Имя Пользователя')),
                ('username', models.CharField(max_length=100, verbose_name='Username Telegram')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
            ],
        ),
    ]
